Rephrasing
SharezoneApp/blog pull request #2
Opened 2021-02-27 18:16 UTC by Th3Ph4nt0m

I really like your text, but unfortunately there were still some grammatical errors that "polluted" the text. I rephrased these sentences and also inserted 2 helpful links:

1. https://www.digitalengagiert.de/
2. https://apkpure.com/apkpure-app.html

2021-03-12 16:39 UTC, nilsreichardt approved these changes
Hi @Th3Ph4nt0m 👋  

Sorry for the late response! 
Many thanks for this PR! I like it 😄

LGTM

2021-03-12 20:03 UTC, Jonas-Sander requested changes
Mensch, ich fühl mich wieder wie in der Schule! Danke, dass du die Fehler angeguckt und beseitigt hast :)    
2 Sachen waren da noch, die ich ansonsten aber auch fixen kann. Nils muss auch noch bei meiner Frage zustimmen, dann merge ich das.   

Ich gucke mal, dass ich in Zukunft Notifikationen kriege, weiß auch nicht, warum ich da nichts bekommen habe.

2021-03-12 20:03 UTC, Jonas-Sander commented on _posts/2020-02-12-Sharezone-In-Review-Feb-Part-1.md
> +Beides schonmal besser als gar nichts zu wissen :)\
Nenenene :D https://www.korrekturen.de/beliebte_fehler/schonmal.shtml
```suggestion
Beides schon mal besser als gar nichts zu wissen :)\
```

2021-03-12 20:03 UTC, Jonas-Sander commented on _posts/2020-02-12-Sharezone-In-Review-Feb-Part-1.md
> +Bisher ist Sharzone aber noch nicht über die [AppGallery]https://appgallery.huawei.com) verfügbar, dafür müssen wir noch ein bisschen Arbeit machen. Solange kann man sich Sharezone [hier](https://apk
@nilsreichardt 

> Dafür könnt ihr aber die [APKPure-App](https://apkpure.com/apkpure-app.html), einen alternativen App-Store, nutzen).

Geht das für dich klar? Ich kenn mich halt nicht damit aus und will nichts empfehlen was ich nicht kenne. Hast du damit Erfahrungen gemacht?:)

2021-03-12 20:03 UTC, Jonas-Sander commented on _posts/2020-02-26-Sharezone-In-Review-Feb-Part-2.md
> +In diesem Auschnitt der alten Slide, dass sie zu viel Text hatte, als dass man alles bei einer Präsentation lesen könnte. Man konzentiert sich ja auch aufs zuzuhören. Besser ist es, auf Slides eher B
Danke, ich glaube du hattest da aber aus Versehen was ausgelassen.   
Ich habs noch n paar kleine Sachen umgeändert :) 

```suggestion
Bei diesem alten Ausschnitt erkannt man, dass dieser zu viel Text hatte, als dass man alles während der Präsentation lesen könnte. Man konzentiert sich ja auch aufs zuhören. Besser ist es, eher Bilder, Icons und wenig Text zu benutzen - das meiste spricht man ja schließlich in der Live-Präsentation selbst an, wodurch der Text redundant wäre.
```

2021-03-13 00:17 UTC, nilsreichardt commented on _posts/2020-02-12-Sharezone-In-Review-Feb-Part-1.md
> +Bisher ist Sharzone aber noch nicht über die [AppGallery]https://appgallery.huawei.com) verfügbar, dafür müssen wir noch ein bisschen Arbeit machen. Solange kann man sich Sharezone [hier](https://apk
Als ich die Review gemacht hatte, war ich auch überrascht gewesen, dass APK-Pure mittlerweile auch eine eigene App hat. Ich kannte bereits deren Webseite, aber noch nicht deren App.

Prinzipiell zur Seite ist zu sagen, dass dies wohl die exakt die selben Daten zwischen PlayStore und APK-Pure sind, zu mindestens laut [diesem](https://forum.kuketz-blog.de/viewtopic.php?p=34789&sid=35cdebcaf871d45d2b3465526d37be1f#p34789) Forum-Beitrag. Ich nutze die Seite auch schon seit mehreren Jahren und hatte jetzt keine Auffälligkeiten entdeckt.

Die App, also den Store, hatte ich wie eben schon beschrieben auch erst über die PR kennengelernt. Ich konnte mir diesen leider nicht herunterladen / ausprobieren, weil dieser nicht im PlayStore gelistet wird (vermutlich weil alternative Stores nicht im PlayStore vertrieben werden dürfen, weil ja ansonsten die Prüfung von Google easy umgangen werden kann) und durch das Advanced Security Program von Google kann ich keine Apps außerhalb vom Google Play Store herunterladen kann. 

Da die Seite an sich sauber aussieht, würde ich vermuten, dass die App es ebenfalls ist. Zudem löst diese das Problem, dass man nicht mehr manuell die APKs herunterladen muss, wenn man Sharezone nicht über den PlayStore heruntergeladen hat, was ziemlich cool ist.

2021-03-13 18:09 UTC, merged

2021-03-13 18:09 UTC, Jonas-Sander commented
Danke!:)